databases:
  - name: attendance-db
    plan: free
    databaseName: attendance_system
    user: attendance_user

services:
  - type: web
    plan: free
    name: attendance-system
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn attendance_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
